name: alerix_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Persistencia
  shared_preferences: ^2.2.2
  
  # Ubicación
  geolocator: ^12.0.0
  
  # URL Launcher (WhatsApp)
  url_launcher: ^6.3.0
  
  # Audio
  audioplayers: ^6.0.0
  
  # Selector de archivos
  file_picker: ^8.0.0
  
  # Permisos
  permission_handler: ^11.0.0
  
  # Directorio de documentos
  path_provider: ^2.1.0

  # Notificaciones locales
  flutter_local_notifications: ^16.3.0

  flutter_overlay_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/alarm.mp3
    - assets/images/logo.png
    - assets/sounds/alarm1.mp3
    - assets/sounds/alarm2.mp3
    - assets/sounds/siren.mp3
    - assets/sounds/bell.mp3
    - assets/sounds/alert.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true